server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name rps.flappycat.fun _;
    root /home/ubuntu/app/frontend/dist;
    index index.html;

    # React Client Router Fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Node REST API Reverse Proxy
    location /api/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_cache_bypass;
    }

    # Socket.io WebSocket Reverse Proxy
    location /socket.io/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_cache_bypass;
        proxy_read_timeout 86400;
    }
}
